### ISSUE TITLE
Use composer for autoloading

### ISSUE THREAD

**Issue by thiagooak** [abarretti/AnthonyBarretti#3]
https://getcomposer.org/

**Comment by abarretti** [comment]
created a new branch called 'composer' with PS-4 autoloading. SILEX framework with bootstrap is next :)

**Comment by thiagooak** [comment]
@abarretti can you create a pull request from the composer branch?

That way it is easier for me to add any comments

You can follow these instructions

https://help.github.com/articles/creating-a-pull-request/#creating-the-pull-request
