### ISSUE TITLE
Use a templating Engine to separate your view from your controllers and models

### ISSUE THREAD

**Issue by thiagooak** [abarretti/AnthonyBarretti#4]
I suggest: https://twig.symfony.com/

**Comment by abarretti** [comment]
I'm a little stuck on using Silex with Twig. The only changing variable to the model for my site is the variable 'page'. Is there a way to insert the variable directly into the twig->render function?

Instead of doing this:
$app->get('/', function () use ($app) {
	return $app['twig']->render('index.twig', array(
		'page' => 'home'
		));
});

I want to do this:
$app->get('/', function () use ($app) {
	return $app['twig']->render('index.twig', array(
		'page' => $model->page
		));
});
 
where $model->page = 'home'

Is there a way to insert the variable directly into the twig array?

**Comment by thiagooak** [comment]
That should work, but your model would need to be set within that context
or to the use statement

like

$app->get('/', function () use ($app, $model) {
...

On Nov 7, 2017 9:03 PM, "Anthony Barretti" <notifications@github.com> wrote:

I'm a little stuck on using Silex with Twig. The only changing variable to
the model for my site is the variable 'page'. Is there a way to insert the
variable directly into the twig->render function?

Instead of doing this:
$app->get('/', function () use ($app) {
return $app['twig']->render('index.twig', array(
'page' => 'home'
));
});

I want to do this:
$app->get('/', function () use ($app) {
return $app['twig']->render('index.twig', array(
'page' => $model->page
));
});

where $model->page = 'home'

Is there a way to insert the variable directly into the twig array?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/abarretti/AnthonyBarretti/issues/4#issuecomment-342604827>,
or mute the thread

**Comment by abarretti** [comment]
Cool! It works. Should my entire view be in a 1 twig file? Or should I break it down into head, header, main, footer?

**Comment by abarretti** [comment]
Nevermind. I guess I should create a base and insert child elements as follows: https://twig.symfony.com/doc/2.x/tags/extends.html

**Comment by thiagooak** [comment]
yeah, that's right. using the base template is the way to go
