### ISSUE TITLE
Create a pre-commit hook to enforce the use of PSR2

### ISSUE THREAD

**Issue by thiagooak** [abarretti/AnthonyBarretti#6]
PSR2 is a coding style guide very popular in the PHP community - http://www.php-fig.org/psr/psr-2/

PHPCS is a code sniffer that helps you check your code for code style problems https://github.com/squizlabs/PHP_CodeSniffer

A Pre Commit Hook is a script that runs before you commit things and is a popular place to add code style validations
https://git-scm.com/book/gr/v2/Customizing-Git-Git-Hooks

You should have a sample pre-commit file on your repo. Look into `.git/hooks/pre-commit.sample`

**Comment by abarretti** [comment]
I am not entirely understanding how to add psr-2 to the pre-commit file. I have removed the .sample suffix from the file.

I found the following shell in a forum. Do I just add it to the pre-commit file below the other code?
#psr-2 compliance
while read -r file;
do
  file=${file:1}
  if [[ $file = *.php ]];
  then    
    php-cs-fixer fix "$file" --level=psr2
    git add "$file"
  fi
done < <(git diff --cached --name-status --diff-filter=ACM)

**Comment by thiagooak** [comment]
To start you could forget about the pre commit hook and just run phpcs
manually to look for code style violations on your code.

The hook is just a bit of automation around it.

The example you mentioned runs the fixer. What you would want is a hook
that passes (allow you to commit) if the code has no style violations and
fails (blocks you from commiting) otherwise

**Comment by abarretti** [comment]
Finally figured it out :) I'm about to create a pull request.

Also, I really like the Codecourse videos. I find them very helpful.
https://www.youtube.com/watch?v=FGs-mAI4oPk
